### ISSUE TITLE
Extension RoadMap

### ISSUE THREAD

**Issue by leyouaitools** [leyouaitools/aimangatranslator#1]
### Extension
- [x] Implement upload and translation
- [x] Chrome extension
- [x] Microsoft Edge extension
- [ ] Safari extension
- [ ] Firefox extension
- [ ] Adapt the following websites for real-time translation:
  - [ ] Pixiv 
  - [ ] MANGA Plus by SHUEISHA
  - [ ] Zebrack by SHUEISHA
  - [ ] ReadComicOnline
  - [ ] FANBOX
  - [ ] COMIC FUZ
  - [x] MangaDex
  - [ ] MANGABUDDY 
  - [ ] E-Hentai
  - [ ] Yamibo 
  - [ ] Copymanga 
  - [ ] ShonenJumpPlus
  - [ ] Heros Web
  - [ ] Comic Days
  - [ ] Comic Top
  - [ ] ComicWalker
  - [ ] Web Ace
  - [ ] Antbyw
  - [ ] Zerobywzz
  - [ ] Jmanga
  - [ ] DMZJ (动漫之家)
  - [ ] Wnacg
  - [ ] Twitter Comic
  - [ ] nHentai
  - [ ] MANGA DISTRICT
  - [ ] MangaZ
  - [ ] PASH UP
  - [ ] COLAMANGA
  - [ ] CP-Library
  - [ ] Hitomi
  - [ ] GANGAN ONLINE
  - [ ] Manga18
  - [ ] Fhentai
  - [ ] BATOTO
  - [ ] All Manga
  If you want to add more websites to adapt, you can submit them in the following format:
Website address: [Please fill in here]
Note: The submitted address should ensure that the comics can be loaded normally and there are no access restrictions. If the website requires an account and password to adapt, you can leave your contact information and I will contact you for details.

**Comment by iqsilva** [comment]
@leyouaitools Website address: http://mangareader.to

**Comment by s87343472** [comment]
> [@leyouaitools](https://github.com/leyouaitools) Website address: http://mangareader.to

OK, let me see how to adapt
